name: Deploy to ECR(Entry Container Registry)

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: make directory for prepare download
        run: |
          mkdir -p ./src/main/resources/fonts
          mkdir -p ./src/main/resources/secrets

      - name: download certificate for cloudfront url
        working-directory: ./src/main/resources/secrets
        run: |
          wget \
          --http-user=${{ secrets.STATIC_USERNAME }} \
          --http-password=${{ secrets.STATIC_PASSWORD }} \
          ${{ secrets.CERTIFICATE_URL }}

      - name: download font archieve for pdf generating
        working-directory: ./src/main/resources
        run: |
          wget \
          --http-user=${{ secrets.STATIC_USERNAME }} \
          --http-password=${{ secrets.STATIC_PASSWORD }} \
          ${{ secrets.FONT_URL }}

      - name: upzip the font archieve
        working-directory: ./src/main/resources
        run: |
          unzip husky_fonts.zip -d ./fonts && rm husky_fonts.zip

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --info -Dspring.profiles.active=local

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: husky
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          tags: "latest"
